App/models/favorite.py
from App.database import db
from datetime import datetime, timezone

class Favorite(db.Model):
  id = db.Column(db.Integer, primary_key=True)
  user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
  recipe_id = db.Column(db.Integer, db.ForeignKey('recipe.id'), nullable=False)

  def __init__(self, user_id, recipe_id):
      self.user_id = user_id
      self.recipe_id = recipe_id
      self.date_added = datetime.now(timezone.utc)
      self.recipes = []

  def get_json(self):
    return{
        'id': self.id,
        'recipe_id': self.recipe_id,
        'user_id': self.user_id
    }

App/models/user.py
from werkzeug.security import check_password_hash, generate_password_hash
from App.database import db

class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(20), unique=True, nullable=False)
    password = db.Column(db.String(60), nullable=False)
    recipes = db.relationship('Recipe', backref='author', lazy=True)
    ingredients = db.relationship('Ingredient', backref='owner', lazy=True)
    favorites = db.relationship('Favorite', backref='user', lazy=True)
    ratings = db.relationship('Rating', backref='user', lazy=True)

    def __init__(self, username, password ):
        self.username = username
        self.set_password(password)

    def get_json(self):
        return{
            'id': self.id,
            'username': self.username
        }

    def set_password(self, password):
        """Create hashed password."""
        self.password = generate_password_hash(password)

    def check_password(self, password):
        """Check hashed password."""
        return check_password_hash(self.password, password)

App/controllers/favorite.py
from App.models.favorite import Favorite
from App.database import db

def create_favorite(user_id, recipe_id):
    new_favorite = Favorite(user_id=user_id, recipe_id=recipe_id)
    db.session.add(new_favorite)
    db.session.commit()
    return new_favorite

def remove_favorite(user_id, recipe_id):
    favorite = Favorite.query.filter_by(user_id=user_id, recipe_id=recipe_id).first()
    if favorite:
        db.session.delete(favorite)
        db.session.commit()
        return True
    return False

def update_favorite(user_id, recipe_id):
    favorite = Favorite.query.filter_by(user_id=user_id, recipe_id=recipe_id).first()
    if favorite:
        db.session.add(favorite)
        db.session.commit()
        return favorite
    return None

def get_favorite(id):
    return Favorite.query.get(id)

def get_all_favorites_by_user(user_id):
    return Favorite.query.filter_by(user_id=user_id).all()

App/controllers/recipe.py
from App.models.recipe import Recipe
from App.models.RecipeIngredient import RecipeIngredient
from App.database import db
import requests
#import json


def create_recipe(title, instructions, category, image_url, user_id, ingredients):
    new_recipe = Recipe(title=title,instructions=instructions, category=category, image_url=image_url, user_id=user_id)
    db.session.add(new_recipe)
    if ingredients:
     for ingredient in ingredients:
        new_recipe.add_ingredient(ingredient['ingredient'], ingredient['quantity'], ingredient['unit'])
    #db.session.commit()
    #return new_recipe
    db.session.add(new_recipe)
    db.session.flush()
    db.session.commit()
    return new_recipe

def get_recipe(id):
    return Recipe.query.get(id)

def get_all_recipes():
    return Recipe.query.all()

def update_recipe(id, title, instructions, category, image_url, ingredients):
    recipe = get_recipe(id)
    if recipe:
        recipe.title = title
        recipe.instructions = instructions
        recipe.category = category
        recipe.image_url = image_url
        if ingredients:
            recipe.ingredients = []
            for ingredient in ingredients:
                recipe.add_ingredient(ingredient['ingredient'], ingredient['quantity'], ingredient['unit'])
        db.session.add(recipe)
        return db.session.commit()
    return None

def delete_recipe(id):
    recipe = get_recipe(id)
    if recipe:
        db.session.delete(recipe)
        return db.session.commit()
    return None

def get_recipes_by_user(user_id):
    return Recipe.query.filter_by(user_id=user_id).all()

def add_ingredient_to_recipe(recipe_id, ingredient, quantity, unit):
    recipe = get_recipe(recipe_id)
    if recipe:
        recipe.add_ingredient(ingredient, quantity, unit)
        return recipe
    return None 

def get_recipes_by_ingredient(ingredient_id):
    return Recipe.query.join(RecipeIngredient).filter(RecipeIngredient.ingredient_id == ingredient_id).all()  # type: ignore  

def get_recipes_by_category(category):
    return Recipe.query.filter_by(category=category).all()

def get_recipes_by_title(title):
    return Recipe.query.filter(Recipe.title.ilike(f'%{title}%')).all() #type: ignore

def favorite_recipe(user_id, recipe_id):
    recipe = get_recipe(recipe_id)
    if recipe:
        recipe.add_favorite(user_id)
        return recipe
    return None

def unfavorite_recipe(user_id, recipe_id):
    recipe = get_recipe(recipe_id)
    if recipe:
        recipe.remove_favorite(user_id)
        return recipe
    return None

def rate_recipe(user_id, recipe_id, score):
    recipe = get_recipe(recipe_id)
    if recipe:
        recipe.add_rating(user_id, score)
        return recipe
    return None

def fetch_api_recipes(search_term):
    url = f'https://www.themealdb.com/api/json/v1/1/search.php?s={search_term}'
    response = requests.get(url)
    if response.status_code != 200:
        print('Error fetching recipes from API')
        return []

    data = response.json()

    recipes = []
    for meal in data.get('meals', []):
        recipe = {
            'title': meal['strMeal'],
            'instructions': meal['strInstructions'],
            'category': meal['strCategory'],
            'image_url': meal['strMealThumb'],
            'ingredients': []
        }
        for i in range(1, 21):
            ingredient = meal[f'strIngredient{i}']
            measure = meal[f'strMeasure{i}']
            if ingredient:
                recipe['ingredients'].append({'ingredient': ingredient, 'measure': measure})
        recipes.append(recipe)
        db.session.add(recipe)
        db.session.commit()

    return recipes

def search_recipes(search_term):
    recipes = get_recipes_by_title(search_term)
    if not recipes:
        recipes = fetch_api_recipes(search_term)
        return recipes
    return recipes

App/controllers/user.py
from App.models import User
from App.database import db
from sqlalchemy.exc import SQLAlchemyError

def create_user(username, password):
    try:
        newuser = User(username=username, password=password)
        db.session.add(newuser)
        db.session.commit()
        return newuser
    except SQLAlchemyError as e:
        print(f"Error creating user: {e}")
        db.session.rollback()
        return None


def get_user_by_username(username):
    try:
        return User.query.filter_by(username=username).first()
    except SQLAlchemyError as e:
        print(f"Error fetching user by username: {e}")
        return None


def get_user(id):
    try:
        return User.query.get(id)
    except SQLAlchemyError as e:
        print(f"Error fetching user by ID: {e}")
        return None


def get_all_users():
    try:
        return User.query.all()
    except SQLAlchemyError as e:
        print(f"Error fetching all users: {e}")
        return []


def get_all_users_json():
    try:
        users = User.query.all()
        if not users:
            return []
        return [user.get_json() for user in users]
    except SQLAlchemyError as e:
        print(f"Error fetching users in JSON: {e}")
        return []


def update_user(id, username):
    try:
        user = get_user(id)
        if user:
            user.username = username
            db.session.add(user)
            db.session.commit()
            return user
        else:
            print(f"No user found with ID {id}")
            return None
    except SQLAlchemyError as e:
        print(f"Error updating user: {e}")
        db.session.rollback()
        return None

App/views/auth.py
from flask import Blueprint, render_template, jsonify, request, flash, redirect, url_for, make_response #send_from_directory, 
from flask_jwt_extended import jwt_required, current_user, unset_jwt_cookies, set_access_cookies, create_access_token
from App.controllers.user import * # type: ignore
from flask import Response as FlaskResponse


from.index import * # type: ignore

from App.controllers import (
    login,
    create_user
)

auth_views = Blueprint('auth_views', __name__, template_folder='../templates')



'''
Page/Action Routes
'''    
@auth_views.route('/users', methods=['GET'])
def get_user_page():
    users = get_all_users() # type: ignore
    if not users:
        flash('No users found')
    return render_template('users.html', users=users)

@auth_views.route('/identify', methods=['GET'])
@jwt_required()
def identify_page():
    return render_template('message.html', title="Identify", message=f"You are logged in as {current_user.id} - {current_user.username}")

'''
@auth_views.route('/login', methods=['POST'])
def login_action():
    data = request.form
    token = login(data['username'], data['password'])

    if not token:
        flash('Bad username or password given'), 401
    else:
        flash('Login Successful')
        response = redirect(request.referrer)
        set_access_cookies(response, token) 
    return response
'''

@auth_views.route('/login', methods=['POST'])
def login_action():
    data = request.form
    token = login(data['username'], data['password'])

    if not token:
        flash('Bad username or password given')
        return redirect(request.referrer), 401

    response = make_response(redirect(url_for('index_views.home')))
    flash('Login Successful')
    set_access_cookies(response, token) # type: ignore
    return response

@auth_views.route('/register', methods=['POST'])
def register_action():
    data = request.form
    create_user(data['username'], data['password'])
    flash('User Registered')
    return render_template('index.html')


@auth_views.route('/logout', methods=['GET'])
def logout_action():
    response = render_template('index.html')
    flash("Logged Out!")
    unset_jwt_cookies(response) # type: ignore
    return response

'''
API Routes
'''

@auth_views.route('/api/login', methods=['POST'])
def user_login_api():
    data = request.json
    if not data:
        return jsonify(message="Please provide user details"), 400

    token = login(data['username'], data['password'])
    if not token:
        return jsonify(message='bad username or password given'), 401
    response = jsonify(access_token=token) 
    set_access_cookies(response, token)
    return response

@auth_views.route('/api/identify', methods=['GET'])
@jwt_required()
def identify_user():
    return jsonify({'message': f"username: {current_user.username}, id : {current_user.id}"})

@auth_views.route('/api/logout', methods=['GET'])
def logout_api():
    response = jsonify(message="Logged Out!")
    unset_jwt_cookies(response)
    return response

App/views/favorite.py
from flask import Blueprint, render_template, redirect, url_for, flash
from flask_jwt_extended import jwt_required, get_jwt_identity
from App.controllers import * #type: ignore

favorite_view = Blueprint('favorite_view', __name__)

@favorite_view.route('/favorites', methods=['GET'])
@jwt_required()
def get_favorites():
    #this is to query the db for the user's favorite recipes and render them in the favorites template
    user_id = get_jwt_identity()
    favorites = get_all_favorites_by_user(user_id) #type: ignore
    return render_template('favorites.html', favorites=favorites)

@favorite_view.route('/favorites/add/<int:recipe_id>', methods=['POST'])
@jwt_required()
def add_favorite(recipe_id):
    #this is to add a recipe to the user's favorites. adds the favorite to the db and redirects to the favorites page
    user_id = get_jwt_identity()
    create_favorite(user_id, recipe_id) #type: ignore
    flash('Recipe added to favorites!', 'success')
    return redirect(url_for('favorite_view.get_favorites'))

@favorite_view.route('/favorites/remove/<int:recipe_id>', methods=['POST'])
@jwt_required()
def remove_favorite(recipe_id):
    #this is to remove a recipe from the user's favorites. removes the favorite from the db and redirects to the favorites page
    user_id = get_jwt_identity()
    remove_favorite(user_id, recipe_id)
    flash('Recipe removed from favorites!', 'success')
    return redirect(url_for('favorite_view.get_favorites'))

App/views/recipe.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_jwt_extended import jwt_required, get_jwt_identity
from App.models.recipe import Recipe
from App.controllers.recipe import * #type: ignore

recipe_view = Blueprint('recipe_view', __name__)

@recipe_view.route('/recipes', methods=['GET'])
@jwt_required()
def recipes():
    #this is to query all recipes belonging to the user and render them in the recipes template 
    user_id = get_jwt_identity()
    recipes = Recipe.query.filter_by(user_id=user_id).all()
    return render_template('recipes.html', title='Recipes', recipes=recipes)

@recipe_view.route('/recipes/<int:recipe_id>', methods=['GET'])
@jwt_required()
def recipe(recipe_id):
    #this is to query a single recipe by id and render it in the recipe template
    user_id = get_jwt_identity()
    recipe = Recipe.query.get_or_404(recipe_id)
    if recipe.user_id != user_id:
        flash('You do not have permission to view this recipe.', 'danger')
        return redirect(url_for('recipe_view.recipes'))
    return render_template('recipe.html', title=recipe.title, recipe=recipe)

@recipe_view.route('/recipes/new', methods=['POST'])
@jwt_required()
def new_recipe():
    #this isto create a new recipe for the user using form data. saves data to db and redirects them to the recipes page
    user_id = get_jwt_identity()
    title = request.form.get('title')
    instructions = request.form.get('instructions')
    category = request.form.get('category')
    image_url = request.form.get('image_url') or None

    new_recipe = create_recipe(title, instructions, category, image_url, user_id, []) #type: ignore
    flash('Your recipe has been created!', 'success')
    return redirect(url_for('recipe_view.recipes'))

@recipe_view.route('/recipes/update/<int:recipe_id>', methods=['POST'])
@jwt_required()
def update_recipe(recipe_id):
    #this is to update a recipe for the user using form data. saves data to db and redirects them to the recipes page
    user_id = get_jwt_identity()
    recipe = Recipe.query.get_or_404(recipe_id)
    if recipe.user_id != user_id:
        flash('You do not have permission to update this recipe.', 'danger')
        return redirect(url_for('recipe_view.recipes'))

    recipe = update_recipe(recipe_id, request.form.get('title'), request.form.get('instructions'), request.form.get('category'), request.form.get('image_url') or None, [])

    flash('Your recipe has been updated!', 'success')
    return redirect(url_for('recipe_view.recipes'))


@recipe_view.route('/recipes/delete/<int:recipe_id>', methods=['POST'])
@jwt_required()
def delete_recipe(recipe_id):
    #this is to delete a recipe for the user. deletes data from db and redirects them to the recipes page
    user_id = get_jwt_identity()
    recipe = Recipe.query.get_or_404(recipe_id)
    if recipe.user_id != user_id:
        flash('You do not have permission to delete this recipe.', 'danger')
        return redirect(url_for('recipe_view.recipes'))

    delete_recipe(recipe_id)
    flash('Your recipe has been deleted!', 'success')
    return redirect(url_for('recipe_view.recipes'))

@recipe_view.route('/recipes/search', methods=['GET'])
@jwt_required()
def search_recipes():
    #this is to search for recipes by title or category
    user_id = get_jwt_identity()
    if user_id is None:
        flash('You must be logged in to search for recipes.', 'danger')
        return redirect(url_for('auth_views.login_action'))

    query = request.args.get('query')
    recipes = fetch_api_recipes(query) #type: ignore

    return render_template('recipes.html', title='Recipes', recipes=recipes)

App/views/user.py
from flask import Blueprint, render_template, jsonify, request, send_from_directory, flash, redirect, url_for
#from flask_jwt_extended import jwt_required, current_user as jwt_current_user

#from.index import index_views

from App.controllers import (
    create_user,
    get_all_users,
    get_all_users_json,
    #jwt_required
)

user_views = Blueprint('user_views', __name__, template_folder='../templates')

@user_views.route('/users', methods=['GET'])
def get_user_page():
    users = get_all_users()
    return render_template('users.html', users=users)

@user_views.route('/users', methods=['POST'])
def create_user_action():
    data = request.form
    flash(f"User {data['username']} created!")
    create_user(data['username'], data['password'])
    return redirect(url_for('user_views.get_user_page'))

@user_views.route('/api/users', methods=['GET'])
def get_users_action():
    users = get_all_users_json()
    return jsonify(users)

@user_views.route('/api/users', methods=['POST'])
def create_user_endpoint():
    data = request.json
    if not data:
        return jsonify(message="Please provide user details"), 400
    user = create_user(data['username'], data['password'])
    return jsonify({'message': f"user {user.username} created with id {user.id}"})

@user_views.route('/static/users', methods=['GET'])
def static_user_page():
  return send_from_directory('static', 'static-user.html')

App/templates/401.html
{% extends "layout.html" %}
{% block title %}Not Authorized{% endblock %}
{% block page %}Not Auhtorized{% endblock %}

{{ super() }}

{% block content %}
<div class="container">
    <div class="row" style="margin-top: 10%;">
        <div class="col s12 m10 offset-m1">
            <div class="card-content">
                <h1>401 - Not Authorized</h1>
                <p>You do not have permission to access this resource. Please check your credentials and try again.</p>
                <p>{{error}}</p>
            </div>
            <div class="card-action">
                <a href="/" class="waves-effect waves-light btn">Go Home</a>
                <a href="javascript:history.back()" class="waves-effect waves-light btn">Go Back</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

App/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Welcome to Pantry Pal</title>
  <link href="https://fonts.googleapis.com/css2?family=Chewy&family=Poppins:wght@400;500&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="styles.css">
  <style>
    * {
      box-sizing: border-box;
    }
    body, html {
      height: 100%;
      margin: 0;
      font-family: 'Poppins', sans-serif;
      background-image: url('https://img.freepik.com/premium-vector/watercolor-food-set-illustration_162279-2881.jpg');
      background-size: cover;
      background-repeat: no-repeat;
      background-position: center;
    }

    .welcome-container {
      height: 100%;
      background-color: rgba(255, 255, 255, 0.85);
      display: flex;
      flex-direction: column;
      justify-content: center;
      align-items: center;
      animation: fadeIn 1.5s ease-in-out;
      padding: 0 20px;
      text-align: center;
    }

    .welcome-title {
      font-family: 'Chewy', cursive;
      color: #FF6B6B;
      font-size: 4rem;
      margin-bottom: 10px;
      animation: slideInDown 1s ease;
      text-shadow: 1px 1px 2px rgba(0,0,0,0.1);
    }

    .welcome-subtitle {
      font-size: 1.4rem;
      color: #333;
      background-color: rgba(255,255,255,0.8);
      padding: 15px 25px;
      border-radius: 12px;
      margin-bottom: 40px;
      box-shadow: 0 5px 15px rgba(0,0,0,0.05);
      animation: fadeInUp 1.5s ease;
    }

    .divider {
      width: 200px;
      height: 4px;
      background-color: #FFD166;
      border-radius: 5px;
      margin: 20px 0;
      animation: fadeIn 2s ease;
    }

    .welcome-buttons {
      display: flex;
      justify-content: center;
      gap: 20px;
    }

    .welcome-buttons form {
      display: flex;
      flex-direction: column;
      align-items: center;
      padding: 15px;
      background-color: rgba(255, 255, 255, 0.9);
      border-radius: 8px;
      box-shadow: 0 5px 15px rgba(0,0,0,0.1);
    }

    .welcome-buttons button {
      background-color: #FF6B6B;
      color: white;
      padding: 12px 25px;
      border: none;
      border-radius: 25px;
      font-weight: bold;
      cursor: pointer;
      transition: all 0.3s ease;
      animation: fadeInUp 2s ease;
      width: 100%;
      margin-top: 10px;
    }

    .welcome-buttons button:hover {
      background-color: #e65353;
      transform: scale(1.05);
    }

    .welcome-buttons input {
      margin: 8px 0;
      padding: 8px;
      width: 200px;
      border: 1px solid #ccc;
      border-radius: 4px;
      font-size: 14px;
    }

    .welcome-buttons label {
      color: #333;
      font-size: 14px;
      margin-bottom: 5px;
    }

    .error-messages {
      color: red;
      font-size: 14px;
      margin-bottom: 20px;
      background-color: rgba(255, 255, 255, 0.9);
      padding: 10px;
      border-radius: 8px;
      max-width: 400px;
      text-align: left;
    }

    /* Animations */
    @keyframes fadeIn {
      from {opacity: 0;}
      to {opacity: 1;}
    }

    @keyframes fadeInUp {
      from {
        opacity: 0;
        transform: translateY(30px);
      }
      to {
        opacity: 1;
        transform: translateY(0);
      }
    }

    @keyframes slideInDown {
      from {
        transform: translateY(-50px);
        opacity: 0;
      }
      to {
        transform: translateY(0);
        opacity: 1;
      }
    }
  </style>
</head>
<body>

  <div class="welcome-container">
    <div class="welcome-title">Pantry Pal</div>
    <div class="divider"></div>
    <div class="welcome-subtitle">
      Your personal kitchen companion.<br>
      Save ingredients, find recipes, and get inspired!
    </div>
    {% if get_flashed_messages() %}
        <div class="error-messages">
            {% for message in get_flashed_messages() %}
                <p>{{ message }}</p>
            {% endfor %}
        </div>
    {% endif %}
    <div class="welcome-buttons">
      <form method="POST" action="{{ url_for('auth_views.login_action') }}">
        <label for="login-username">Username</label>
        <input type="text" id="login-username" name="username" required>
        <label for="login-password">Password</label>
        <input type="password" id="login-password" name="password" required>
        <button type="submit">Log In</button>
      </form>
      <form method="POST" action="{{ url_for('auth_views.register_action') }}">
        <label for="register-username">Username</label>
        <input type="text" id="register-username" name="username" required>
        <label for="register-password">Password</label>
        <input type="password" id="register-password" name="password" required>
        <button type="submit">Sign Up</button>
      </form>
    </div>
  </div>

</body>
</html>

App/templates/message.html
{% extends "layout.html" %}
{% block title %}{{title}}{% endblock %}
{% block page %}{{title}}{% endblock %}

{{ super() }}

{% block content %}
<div class="container">
    <div class="row" style="margin-top: 10%;">
        <div class="col s12 m10 offset-m1">
            <p>{{message}}</p>
        </div>
    </div>
</div>
{% endblock %}

App/templates/navbar.html
<link href="https://fonts.googleapis.com/css2?family=Chewy&display=swap" rel="stylesheet">

<style>
    .designNav {
    position: relative; /* ensures dropdown isn't cut off */
    z-index: 10;
    background-color: bisque;
}
    nav {
        display: flex;
        align-items: center;
        justify-content: space-between;
        flex-wrap: wrap;
        gap: 1em;
        background-color: bisque;
    }

    nav > * {
        flex-grow: 1;
        flex-shrink: 0;
        min-width: 100px;
        margin: 0 20px;
    }

    nav h1 a {
        font-family: 'Chewy', cursive;
        font-size: 2rem;
        color: #FF6B6B;
        text-decoration: none;
        transition: color 0.3s ease-in-out;
        flex: 0 1 auto; /* Prevent h1 from growing too much */
    }

    nav h1 a:hover {
        color: #e05555;
    }

    .navButton {
        padding: 10px 16px;
        background-color: white;
        color: black;
        font-family: Georgia, serif;
        text-decoration: none;
        border-radius: 8px;
        border: 1px solid #FF6B6B;
        transition: background-color 0.3s, transform 0.2s;
        cursor: pointer;
        width: auto; /* Ensure button only takes up space as needed */
    }

    .navButton:hover {
        background-color: #ffecec;
        transform: scale(1.05);
        font-weight: bold;
    }

    .search-section {
        display: flex;
        gap: 0.5em;
        align-items: center;
        flex: 1 1 200px; /* Allow search section to grow */
    }

    .search-section input {
        width: 100%;
        min-width: 150px;
    }

    .search-section button {
        width: auto;
    }

    .dropdown {
        position: relative;
        flex: 0 0 auto; /* Prevent the dropdown from expanding */
    }

    .avatar {
        width: 50px;
        height: 50px;
        border-radius: 50%;
        cursor: pointer;
    }

    .dropdown-content {
        display: none;
        position: absolute;
        top: 60px;
        right: 0;
        background-color: white;
        min-width: 160px;
        box-shadow: 0px 8px 16px rgba(0, 0, 0, 0.2);
        border-radius: 8px;
        overflow: hidden;
        animation: fadeIn 0.3s ease-in-out;
    }

    .dropdown:hover .dropdown-content,
    .dropdown-content:hover {
        display: block;
    }
    .dropdown {
        position: relative;
        display: inline-block; /* keeps layout inline */
    }

    .dropdown-content a,
    .dropdown-content button {
        display: block;
        padding: 12px 16px;
        text-decoration: none;
        color: black;
        background-color: white;
        border: none;
        width: 100%;
        text-align: left;
        cursor: pointer;
        transition: background 0.3s;
    }

    .dropdown-content a:hover,
    .dropdown-content button:hover {
        background-color: #f0f0f0;
    }

    @keyframes fadeIn {
        from {
            opacity: 0;
            transform: translateY(-10px);
        }
        to {
            opacity: 1;
            transform: translateY(0);
        }
    }

    select, input[type="text"] {
        padding: 6px 10px;
        border: 1px solid #ccc;
        border-radius: 5px;
        font-size: 1rem;
    }

    @media (max-width: 768px) {
        nav {
            flex-direction: column;
            gap: 1em;
            align-items: stretch;
        }

        .navButton, .search-section {
            width: 100%;
        }

        .dropdown-content {
            width: 100%;
        }
    }

</style>

<header class="designNav">
    <nav>
        
        <h1 style="width: 5%;"><a href="home.html">Pantry Pal</a></h1>

        

        <div style="width: 3%;">
            <label for="sortBy">Sort By:</label>
            <select id="sortBy">
                <option value="" selected disabled>-- Select Sort --</option>
                <option value="az">A - Z</option>
                <option value="za">Z - A</option>
            </select>
        </div>

        <div style="width: 5%;">
            <label for="filterBy">Filter By:</label>
            <select name="filterBy" id="filterBy">
                <option value="" selected disabled>-- Select Category --</option>
                <option data-type="category" value="starter">Starter</option>
                <option data-type="category" value="pasta">Pasta</option>
                <option data-type="category" value="side">Side</option>
                <option data-type="category" value="breakfast">Breakfast</option>
                <option data-type="category" value="chicken">Chicken</option>
                <option data-type="category" value="beef">Beef</option>
                <option data-type="category" value="lamb">Lamb</option>
                <option data-type="category" value="pork">Pork</option>
                <option data-type="category" value="goat">Goat</option>
                <option data-type="category" value="seafood">Seafood</option>
                <option data-type="category" value="vegetarian">Vegetarian</option>
                <option data-type="category" value="vegan">Vegan</option>
                <option data-type="category" value="dessert">Dessert</option>
                <option data-type="category" value="miscellaneous">Miscellaneous</option>
                <optgroup label="Cuisine">
                    <option data-type="area" value="chinese">Chinese</option>
                    <option data-type="area" value="indian">Indian</option>
                    <option data-type="area" value="spanish">Spanish</option>
                    <option data-type="area" value="japanese">Japanese</option>
                    <option data-type="area" value="croatian">Croatian</option>
                    <option data-type="area" value="turkish">Turkish</option>
                    <option data-type="area" value="egyptian">Egyptian</option>
                    <option data-type="area" value="filipino">Filipino</option>
                    <option data-type="area" value="tunisian">Tunisian</option>
                    <option data-type="area" value="american">American</option>
                    <option data-type="area" value="italian">Italian</option>
                    <option data-type="area" value="canadian">Canadian</option>
                    <option data-type="area" value="british">British</option>
                    <option data-type="area" value="dutch">Dutch</option>
                    <option data-type="area" value="greek">Greek</option>
                </optgroup>
            </select>
        </div>

        <div style="width: 5%;">
            <a href="random-recipe.html" class="navButton">Random Recipe</a>
        </div>

        <div class="row" style="width: 5%;">
            <section class="search-section">
                <input type="text" placeholder="Search Recipe">
                <button type="submit">Search</button>
            </section>
        </div>

        <div class="dropdown" style="width: 5%;">
            <img src="avatar.jpeg" alt="Avatar" class="avatar">
            <div class="dropdown-content">
                <a href="ingredient.html">Inventory</a>
                <a href="createrecipe.html">Create recipe</a>
                <a href="favorites.html">View favorites</a>
                <a href="{{ url_for('auth_views.logout_action') }}">Logout</a>
            </div>
        </div>
    
    </nav>

    <script>
        const dialog = document.querySelector("dialog");
        document.querySelector("#open-popup")?.addEventListener("click", () => dialog.showModal());
        document.querySelector(".close-btn")?.addEventListener("click", () => dialog.close());
    </script>
</header>